/*
Console To-Do List App (C++)

Features:
- Add tasks
- Mark tasks complete
- Delete tasks
- Show task list (with status)
- Save & load tasks from a file (tasks.txt)

Compile (example):
  g++ -std=c++17 console_todo.cpp -o todo
  ./todo

Author: Generated by ChatGPT
*/

#include <bits/stdc++.h>
using namespace std;

struct Task {
    string desc;
    bool done = false;
};

const string STORAGE_FILE = "tasks.txt";

vector<Task> tasks;

void trim_inplace(string &s) {
    // simple trim
    size_t start = s.find_first_not_of(" \t\n\r");
    size_t end = s.find_last_not_of(" \t\n\r");
    if (start == string::npos) { s.clear(); return; }
    s = s.substr(start, end - start + 1);
}

void load_tasks() {
    tasks.clear();
    ifstream in(STORAGE_FILE);
    if (!in.is_open()) return; // no file yet
    string line;
    while (getline(in, line)) {
        if (line.empty()) continue;
        // format: 0|task description  or 1|task description
        size_t sep = line.find('|');
        if (sep == string::npos) continue;
        string flag = line.substr(0, sep);
        string desc = line.substr(sep + 1);
        trim_inplace(desc);
        Task t;
        t.done = (flag == "1");
        t.desc = desc;
        tasks.push_back(t);
    }
}

void save_tasks() {
    ofstream out(STORAGE_FILE);
    if (!out.is_open()) {
        cout << "Warning: could not save to " << STORAGE_FILE << "\n";
        return;
    }
    for (auto &t : tasks) {
        out << (t.done ? "1" : "0") << "|" << t.desc << "\n";
    }
}

void show_tasks() {
    cout << "\n===== TO-DO LIST =====\n";
    if (tasks.empty()) {
        cout << "(no tasks)\n";
        return;
    }
    for (size_t i = 0; i < tasks.size(); ++i) {
        cout << i + 1 << ". [" << (tasks[i].done ? 'X' : ' ') << "] " << tasks[i].desc << "\n";
    }
}

void add_task() {
    cin.ignore(numeric_limits<streamsize>::max(), '\n'); // clear rest of line
    cout << "Enter new task description: ";
    string desc;
    getline(cin, desc);
    trim_inplace(desc);
    if (desc.empty()) {
        cout << "Empty task not added.\n";
        return;
    }
    tasks.push_back(Task{desc, false});
    cout << "Task added.\n";
}

void mark_complete() {
    if (tasks.empty()) { cout << "No tasks to mark.\n"; return; }
    show_tasks();
    cout << "Enter task number to toggle complete: ";
    int idx;
    if (!(cin >> idx)) { cin.clear(); cin.ignore(numeric_limits<streamsize>::max(), '\n'); cout << "Invalid input.\n"; return; }
    if (idx < 1 || idx > (int)tasks.size()) { cout << "Invalid task number.\n"; return; }
    tasks[idx-1].done = !tasks[idx-1].done;
    cout << "Task " << idx << " marked " << (tasks[idx-1].done ? "complete." : "incomplete.") << "\n";
}

void delete_task() {
    if (tasks.empty()) { cout << "No tasks to delete.\n"; return; }
    show_tasks();
    cout << "Enter task number to delete: ";
    int idx;
    if (!(cin >> idx)) { cin.clear(); cin.ignore(numeric_limits<streamsize>::max(), '\n'); cout << "Invalid input.\n"; return; }
    if (idx < 1 || idx > (int)tasks.size()) { cout << "Invalid task number.\n"; return; }
    cout << "Deleted: " << tasks[idx-1].desc << "\n";
    tasks.erase(tasks.begin() + (idx-1));
}

void show_menu() {
    cout << "\n--- MENU ---\n";
    cout << "1. Show tasks\n";
    cout << "2. Add task\n";
    cout << "3. Mark complete / toggle\n";
    cout << "4. Delete task\n";
    cout << "5. Save and exit\n";
    cout << "6. Exit without saving\n";
    cout << "Choose an option: ";
}

int main() {
    cout << "Simple Console To-Do List (C++)\n";
    load_tasks();
    bool running = true;
    while (running) {
        show_menu();
        int choice;
        if (!(cin >> choice)) {
            cin.clear();
            cin.ignore(numeric_limits<streamsize>::max(), '\n');
            cout << "Please enter a number between 1 and 6.\n";
            continue;
        }
        switch (choice) {
            case 1: show_tasks(); break;
            case 2: add_task(); break;
            case 3: mark_complete(); break;
            case 4: delete_task(); break;
            case 5: save_tasks(); cout << "Saved to " << STORAGE_FILE << ". Exiting.\n"; running = false; break;
            case 6: cout << "Exiting without saving.\n"; running = false; break;
            default: cout << "Unknown option.\n"; break;
        }
    }
    return 0;
}
